#!/usr/bin/python
from  smtplib import SMTP_SSL as SMTP
from email.MIMEText import MIMEText
#import getpass
import sys
SMTPserver="smtp.gmail.com"
sender="savant.2020@gmail.com"
receivers=["savant.2020@gmail.com"]
text_type='plain'
contentf=open("/home/savant/auv-iitb/log.txt","r")
content='''
 \n
'''
fin=open("/home/savant/mailer/.auth","r")
username=fin.readline()
username=username[:len(username)-1]
password=fin.readline()
password=password[:len(password)-1]
fin.close()
x=contentf.readlines()
notgotanycontent=False
if not x:
    notgotanycontent=True
    print "No Content!"
for e in x:
    if not ("commit" in e[:7] or "Author" in e[:7]):
        content=content+e
try:
    message=MIMEText(content,text_type)
    message['Subject']="Re: Daily Update on the Task"
    message['From']= sender
    message['To']=','.join(receivers)
    conn= SMTP(SMTPserver)
    conn.set_debuglevel(False)
    conn.login(username,password)
    #conn.login(raw_input("Username:"),getpass.getpass())
    try:
        if not notgotanycontent:
            print "Sending Mail!"
            conn.sendmail(sender,receivers,message.as_string())
            print "Mail sent!"
        else:
            print "No content"
    finally:
        conn.close()
except Exception, exc:
    sys.exit("mail failes; %s" % str(exc))
